sources:
  repo_0:
    type: codeup
    name: digital-twin-demo_HetS
    endpoint: https://codeup.aliyun.com/68414f6dd42edddb98157f8f/digital-twin-demo.git
    branch: master
    triggerEvents:
      - push
      - mergeRequestMerged
    branchesFilter: ^master.*
    certificate:
      type: serviceConnection
      serviceConnection: r36scsnnt79696ar

defaultWorkspace: repo_0

stages:
  stage_0:
    name: 阶段1
    jobs:
      job_0:
        name: 镜像构建并推送至ACR个人版
        runsOn:
          group: public/cn-hongkong
          labels: linux,amd64
          container: build-steps-public-registry.cn-beijing.cr.aliyuncs.com/build-steps/alinux3:latest
        steps:
          step_0:
            name: 镜像构建并推送至ACR（个人版）
            step: DockerBuildPushACR
            with:
              artifact: artifact
              dockerfilePath: Dockerfile
              dockerRegistry: crpi-07enltghz7a19y5q.cn-hangzhou.personal.cr.aliyuncs.com/digital-twin/cicd
              useVpcAddress: false
              dockerTag: master-${DATETIME}
              region: cn-hangzhou
              cacheType: remote
              serviceConnection: kp1b5fj74esqbtoo
        driven: auto
        plugins: []

  stage_1:
    name: 部署
    jobs:
      job_0:
        name: Docker部署
        component: VMDockerDeploy
        driven: auto
        with:
          useEncode: false
          pauseStrategy: firstBatchPause
          machineGroup: QjMDNRAGk370JZzD
          run: |-
            #!/bin/bash

            # 镜像仓库前缀
            REPO_PREFIX="crpi-07enltghz7a19y5q.cn-hangzhou.cr.aliyuncs.com/digital-twin/cicd"

            # 保留最新 10 个 master 镜像，其他删除
            docker images --format "{{.Repository}}:{{.Tag}} {{.ID}} {{.CreatedAt}}" \
              | grep "^${REPO_PREFIX}:master-" \
              | sort -k3 -r \
              | tail -n +11 \
              | awk '{print $2}' \
              | xargs -r docker rmi -f

            # 清理悬空镜像
            docker image prune --filter "dangling=true" -f

            # 停止并删除旧容器（防止容器名冲突）
            docker rm -f digital-twin-master || true

            # 拉取最新镜像（容器运行时自动拉也可）
            docker pull artifact.image || exit 1

            # 启动新容器
            docker run --restart=always -d \
              -p 8092:80 \
              -p 5858:5858 \
              --name digital-twin-master \
              -v /root/zdy/docker/log/digital-twin:/app/log \
              -e TAG="稳定版服务" \
              -e DB_HOST=39.100.101.252 \
              -e DB_PORT=5434 \
              -e DB_USER=digital_twin_main \
              -e DB_PASSWORD=DHfGKZyYQ2KytsZT \
              -e DB_NAME=digital_twin_main \
              -e INIT_MODE=rebuild \
              -e MQTT_BROKER_HOST=39.100.101.252 \
              -e MQTT_BROKER_PORT=1883 \
              -e SSE_PING_INTERVAL=1 \
              artifact.image
          executeUser: root
          batchNumber: 2
        plugins: []
